// ============================================================
// qianli 项目群能力注册表（dashboard 数据源，单一事实来源）
// 改动机器人权能/指令/监听/权限时同步更新此文件。
// 隐私约定：本文件只写职能与配置键名，不写真实姓名/群号/凭据。
// ============================================================

module.exports = {
  // NAS 上的进程与端口全景（含不归本机管的说明）
  projects: [
    {
      id: 'gateway',
      name: 'feishu-gateway',
      label: '事件接入层（唯一长连接）',
      dir: 'feishu-gateway',
      repo: 'top',            // 跟顶层仓归档
      port: 3010,
      pm2Name: 'feishu-gateway',
      nasDir: '/opt/feishu-gateway',
      deploy: 'npm run push（SFTP 直传）',
      role: '全工作区唯一飞书长连接：统一接收所有事件并路由分发；业务机器人一律不自己连飞书。附带使用统计（/api/usage：谁在用什么功能，按天 30 天，落盘项目外目录）。',
      listening: [
        'im.message.receive_v1 → hub（默认）；例外：工单域（/ticket-* 或 @机器人+「接单」）→ ticket-bot',
        'approval_instance / approval_task → bambu（打印审批联动）/ ticket-bot（接单→审批自动通过）',
        'drive.file.bitable_record_changed_v1 → 按 CONSUMERS 广播给登记的消费者',
        '消息命中路由后顺带记使用统计（不改路由）：GET /api/usage?days=N',
      ],
      commands: ['（无业务指令，纯路由层）'],
      permissions: ['长连接独占（其它服务 FEISHU_USE_LONG_CONNECTION=false）', '消息路由表 DEFAULT_MESSAGE_ROUTES / 消费者登记 CONSUMERS'],
      localRun: null,
      quickActions: [
        { id: 'install', label: 'npm install', cmd: 'npm install', cwd: '' },
      ],
      notes: '改路由/消费者登记先读 .agents/skills/qianli-chat-architecture/SKILL.md；不提供本地启动——本地实例会与 NAS 抢共用应用唯一长连接，生产事件会被随机分流；使用统计 /api/usage 每 30 分钟自动 upsert 到机器人项目看板「网关日活跃/网关功能使用/网关队员活跃」三表（动态广场看板数据源，POST /api/usage-sync/run?force=1 手动补数）',
    },
    {
      id: 'hub',
      name: 'project-management-robot',
      label: '爆米花机-对话型（对话枢纽 + 项目管理）',
      dir: 'ticket-pm/project-management-robot/server',
      repo: 'own',
      port: 3000,
      pm2Name: 'knowledge-tracker',
      nasDir: '/opt/knowledge-tracker',
      deploy: 'npm run push（根目录）',
      role: '所有对话/指令的唯一入口：@对话、基础指令、关键词监听与自动回答、DDL 播报与逾期确认、会议提醒、项目表；专项指令转发各服务。',
      listening: [
        '全部消息事件（gateway 转发）；群聊需 @机器人，私聊直接对话',
        'p2p：DDL 逾期确认回复 → 值日分支（指令/图片，duty-bot 未接管时落回常规流）→ 基础指令（白名单）→ 对话',
        '群：@对话 → 值日群分支（看板带不带 / 均可、@+纯图片静默、非管辖群值日指令回提示）→ 审批群分支 → 基础指令 → 关键词自动回答',
        'GET /api/hub/policy（定制窗口：审批群/值日策略源/回答表范围/播报群全景只读）',
      ],
      commands: [
        '/help /status /test-ddl /keywords /autoreply /history',
        '/approval-* → approval-bot（:3002）',
        '/print-* → bambu（:3001）',
        '值日助手 / 我要请假 / 查询我的下一次值日 / 绑定 X / 是 / 否（口语变体：是的/完成了 等）/ 生成排班表 → duty-bot（:3006；带 / 前缀等效）',
      ],
      windows: [
        { m: 'GET', p: '/api/hub/policy', d: '定制项全景（审批群/值日策略源/回答表范围/播报群）' },
        { m: 'GET', p: '/api/autoreplies/rules?table=group', d: '关键词回答表（未@群消息，可编辑）', kind: 'rules', table: 'group' },
        { m: 'GET', p: '/api/autoreplies/rules?table=mention', d: '@触发回答表（可编辑）', kind: 'rules', table: 'mention' },
        { m: 'POST', p: '/api/autoreplies/rules', d: '新增/更新关键词规则', kind: 'rule-edit' },
        { m: 'POST', p: '/api/autoreplies/rules/delete', d: '删除关键词规则', kind: 'rule-delete' },
        { m: 'POST', p: '/api/autoreplies/enabled', d: '启停回答表', kind: 'toggle' },
        { m: 'GET', p: '/api/keywords/config', d: '关键词监听配置（千里论坛发言记录）' },
      ],
      permissions: [
        '审批群（APPROVAL_CHAT_ID）：整体切换为仅 /approval-*',
        '值日管辖群（duty-bot /api/duty/policy 下发，当前=快递申领群）：hub 基础指令关闭，放行「值日助手」看板与关键词自动回答（@与未@均生效）',
        '私聊基础指令白名单 P2P_COMMAND_OPEN_IDS / P2P_COMMAND_CHAT_IDS（值日指令不限）',
      ],
      localRun: { script: 'src/index.js', cwd: '', env: {} },
      quickActions: [
        { id: 'install', label: 'npm install', cmd: 'npm install', cwd: '' },
        { id: 'test-duty', label: '值日分支 stub 测试', cmd: 'node scripts/stub-test-duty-branch.js', cwd: '' },
      ],
      notes: '关键词自动回答表 .local.json 私有覆盖（真实回答不上传 git）；DDL 播报事件写入动态广场（机器人项目看板）',
    },
    {
      id: 'bambu',
      name: 'bambu-print-reservation',
      label: '打印预约（/print-*）',
      dir: 'bambu-print-reservation',
      repo: 'top',
      port: 3001,
      pm2Name: 'bambu-print-server',
      nasDir: '/opt/bambu-print-server',
      deploy: 'npm run push（纯 SFTP，无 git 步骤）',
      role: '打印预约域：/print-* 指令、预约审批、打印机控制；打印审批联动（审批事件）。',
      listening: ['不消费消息事件（hub 转发 /api/chat/command）', '审批事件（gateway 转发）'],
      commands: ['/print-help /print-status /print-list /print-pending 等'],
      permissions: ['被动指令服务：仅接受 hub 转发'],
      localRun: { script: 'src/index.js', cwd: '', env: {} },
      quickActions: [
        { id: 'install', label: 'npm install', cmd: 'npm install', cwd: '' },
      ],
      notes: 'push 无 git 步骤；版本锚点取顶层归档提交；打印排队/开始/完成/失败事件写入动态广场（机器人项目看板）',
    },
    {
      id: 'approval',
      name: 'approval-bot',
      label: '财务审批（审批群 + 催办）',
      dir: 'approval-bot',
      repo: 'own',
      port: 3002,
      pm2Name: 'approval-bot',
      nasDir: '/opt/approval-bot',
      deploy: 'npm run push',
      role: '财务审批域：审批群 /approval-*、每周财务催办周报（催发票/报销单/转账）、每日待审批提醒、催发票私聊。',
      listening: ['不消费消息事件（hub 转发 /api/chat/command）', 'p2p 回复轮询（催发票延期/无法提交识别）', 'GET /api/approval/policy（定制窗口：流程/审批人白名单/催办参数全景只读）'],
      commands: ['/approval-help /approval-list /approval-pending /approval-status /approval-urge'],
      windows: [
        { m: 'GET', p: '/api/approval/policy', d: '审批流程/审批人白名单/催办参数全景' },
      ],
      permissions: ['仅服务审批群（BOT_CHAT_ID）', '定时任务：周报 / 每日提醒 / 催发票私聊（均过静默闸门）'],
      localRun: { script: 'src/index.js', cwd: '', env: {} },
      quickActions: [
        { id: 'install', label: 'npm install', cmd: 'npm install', cwd: '' },
      ],
      notes: '提醒回落 open_id 已改通用变量名（REMINDER_FALLBACK_OPEN_ID_1/2）',
    },
    {
      id: 'ticket',
      name: 'ticket-bot',
      label: '工单域（播报/接单/结单）',
      dir: 'ticket-pm/ticket-bot',
      repo: 'own',
      port: 3003,
      pm2Name: 'ticket-bot',
      nasDir: '/opt/ticket-bot',
      deploy: 'npm run push',
      role: '工单域：播报到组别群、@接单确认、搬运看板、结单提醒、未结单按负责人组别分桶 API；接单→审批任务自动通过。',
      listening: ['gateway 工单域例外直连：/ticket-* 指令、@机器人+「接单」', '审批事件（接单联动）'],
      commands: ['接单/接单N（群内 @机器人）', '工单指令（/ticket-*）'],
      permissions: ['架构铁律唯一例外：允许消费工单域消息事件'],
      localRun: { script: 'src/index.js', cwd: '', env: {} },
      quickActions: [
        { id: 'install', label: 'npm install', cmd: 'npm install', cwd: '' },
      ],
      notes: '多人接单批次已随 v61（f6f73e2）推送：出站 fetch 15s 超时、审批人解析失败不缓存自愈、接单队列复用全量记录、静默积压挪址 QUIET_BACKLOG_FILE；工单播报/接单/结单/审批自动通过事件写入动态广场（机器人项目看板）；定制窗口 GET /api/tickets/policy 仍未落地（待后续批次，顶层 AGENTS「机器人后端定制窗口」）',
    },
    {
      id: 'duty',
      name: 'duty-bot',
      label: '值日提醒（排班/私信闭环）',
      dir: 'duty-bot',
      repo: 'own',
      port: 3006,
      pm2Name: 'duty-bot',
      nasDir: '/opt/duty-bot',
      deploy: 'npm run push',
      role: '值日域：排班生成与轮转/缺勤补偿、私信提醒与收口、照片凭证写表、值日助手（私信说明/群看板）、/api/duty/brief 数据接口、管辖策略下发（/api/duty/policy）、名册自动读通讯录。',
      listening: ['不消费消息事件（hub 转发 /api/chat/command）', 'GET /api/duty/policy → hub 消费（值日域管辖范畴/生效范畴单一事实来源）', 'GET /api/duty/roster、POST /api/duty/roster/refresh、GET|POST /api/duty/whitelist（名册/白名单定制窗口）'],
      commands: [
        '值日助手（p2p 用法 / group 看板带不带 / 均可，1h 限流）',
        '我要请假 / 查询我的下一次值日 / 绑定 姓名 / 是 / 否（口语变体：是的/好了/完成了/做完了/搞定 等，有当日询问会话时等同「是」）',
        '生成排班表（名册 admin 专用）',
      ],
      windows: [
        { m: 'GET', p: '/api/duty/policy', d: '值日域管辖策略（可在线改写管辖群）' },
        { m: 'POST', p: '/api/duty/policy', d: '管辖范畴在线改写（groupChatIds）', kind: 'policy-edit' },
        { m: 'GET', p: '/api/duty/roster', d: '名册全景（通讯录同步，63 人）' },
        { m: 'POST', p: '/api/duty/roster/refresh', d: '手动刷新通讯录名册', kind: 'action' },
        { m: 'GET', p: '/api/duty/whitelist', d: '白名单（值日排除名单，可增删）', kind: 'whitelist' },
        { m: 'POST', p: '/api/duty/whitelist', d: '白名单增删', kind: 'whitelist-edit' },
        { m: 'GET', p: '/api/duty/brief', d: '昨日/今日值日简报' },
      ],
      permissions: [
        '排班生成权限：名册 admin:true（或 DUTY_ADMIN_OPEN_IDS）',
        '定时任务：D-1 20:00 / 当日 18:30 / 22:00 收口（写表不延迟）/ 00:30 对账（均过静默闸门）',
        '值日域管辖：DUTY_GROUP_CHAT_IDS 管辖群经 /api/duty/policy 下发，hub 群内闸门照此执行',
        '名册自动同步：启动/生成排班前/手动 refresh 读通讯录全员（open_id 直取），whitelist.json 为排除名单',
        '真实名册 config/members.json、whitelist.json 不进 git（push.js 显式 SFTP 上 NAS）',
      ],
      localRun: { script: 'src/index.js', cwd: '', env: {} },
      quickActions: [
        { id: 'install', label: 'npm install', cmd: 'npm install', cwd: '' },
        { id: 'test', label: '排班+闭环+策略 stub 测试', cmd: 'npm run test:schedule && npm run test:flow && npm run test:policy && npm run test:roster', cwd: '' },
        { id: 'table-check', label: '表格字段校验', cmd: 'npm run table:check', cwd: '' },
        { id: 'plaza-tables', label: '动态广场建表（幂等）', cmd: 'node scripts/create-plaza-tables.js', cwd: '' },
      ],
      notes: '表格已接线（机器人项目看板库·值日看板表，字段经 DUTY_FIELD_* 映射）；名册自动读通讯录（64 人全员入册，open_id 直取，whitelist.json 为排除名单——权威在 NAS 侧，push 有备份+守卫，见顶层 AGENTS「运行时数据保护」）；值日完成/请假事件写入动态广场；接口 GET /api/duty/brief、GET /api/duty/policy、GET /api/duty/roster、GET|POST /api/duty/whitelist、POST /api/chat/command（转发载荷带 messageId，消息级幂等全路径生效；返回 {reply, handled}）、/api/bot/test-*',
    },
    {
      id: 'dashboard',
      name: 'qianli-dashboard',
      label: '本地运维台（仅本机）',
      dir: 'dashboard',
      repo: 'top',
      port: 3100,
      pm2Name: null,
      nasDir: null,
      deploy: '仅本机运行（node server.js），不部署 NAS',
      role: '全项目可视化运维：总览仪表台（服务状态矩阵/1h 时间线/24h 可用率/掉线事件、活跃看板=功能使用+功能激活+队员活跃度）、端口职能/权限/指令清单、本地与 NAS 服务状态、运行日志、更新状态；本地测试进程启停；npm push 等快捷指令。',
      listening: ['仅 127.0.0.1，无外部访问'],
      commands: ['HTTP API：/api/overview（含 NAS 状态） /api/stats（总览仪表台：采样史/可用率/掉线事件） /api/activity（活跃看板：网关使用统计+各域 policy 激活聚合） /api/local/:id/start|stop|log /api/action/:id 与 /api/action/:id/log /api/nas/log/:name /api/nas/restart/:name'],
      permissions: ['NAS 凭据直读 approval-bot/.env（不复制、不入库）'],
      localRun: null,
      quickActions: [],
      notes: '本文件 registry.js 是全项目权能清单的单一事实来源',
    },
  ],
};
