// ============================================================
// qianli 项目群能力注册表（dashboard 数据源，单一事实来源）
// 改动机器人权能/指令/监听/权限时同步更新此文件。
// 隐私约定：本文件只写职能与配置键名，不写真实姓名/群号/凭据。
// ============================================================

module.exports = {
  // NAS 上的进程与端口全景（含不归本机管的说明）
  projects: [
    {
      id: 'gateway',
      name: 'feishu-gateway',
      label: '事件接入层（唯一长连接）',
      dir: 'feishu-gateway',
      repo: 'top',            // 跟顶层仓归档
      port: 3010,
      pm2Name: 'feishu-gateway',
      nasDir: '/c/qianli/opt/feishu-gateway',
      deploy: 'npm run push（SFTP 直传）',
      role: '全工作区唯一飞书长连接：统一接收所有事件并路由分发；业务机器人一律不自己连飞书。附带使用统计（/api/usage：谁在用什么功能，按天 30 天，落盘项目外目录）。',
      listening: [
        'im.message.receive_v1 → hub（默认）；例外：工单域（/ticket-* 或 @机器人+「接单」）→ ticket-bot',
        'approval_instance / approval_task → bambu（打印审批联动）/ ticket-bot（接单→审批自动通过）',
        'drive.file.bitable_record_changed_v1 → 按 CONSUMERS 广播给登记的消费者',
        '消息命中路由后顺带记使用统计（不改路由）：GET /api/usage?days=N',
        '群聊被@统计（2026-09-24 团队负载算法数据源）：所有群消息的 mentions 按人按天累计（@机器人/@所有人/私聊不计），GET /api/usage/mentions?days=7 近 N 天自然日滑窗按人求和',
        '各机器人命中点回传功能使用（X-API-Token）：POST /api/usage/report {openId, feature}',
      ],
      commands: ['（无业务指令，纯路由层）'],
      permissions: ['长连接独占（其它服务 FEISHU_USE_LONG_CONNECTION=false）', '消息路由表 DEFAULT_MESSAGE_ROUTES / 消费者登记 CONSUMERS'],
      localRun: null,
      quickActions: [
        { id: 'install', label: 'npm install', cmd: 'npm install', cwd: '' },
      ],
      notes: 'v19 起管理端点鉴权（/api/dispatch 与 /api/usage-sync/run 需 X-API-Token 头，GATEWAY_API_TOKEN 在 .env）+ 长连接启动失败自动重试（2s 起指数退避封顶 5min，30s 轮询自愈）；改路由/消费者登记先读 .agents/skills/qianli-chat-architecture/SKILL.md；不提供本地启动——本地实例会与部署目标(小电脑)抢共用应用唯一长连接，生产事件会被随机分流；使用统计（口径=机器人交互：显式路由/私聊/@机器人）每 30 分钟自动 upsert 到机器人项目看板「网关日活跃」单表（动态广场看板数据源，POST /api/usage-sync/run?force=1 手动补数；网关功能使用/网关队员活跃两表已下线）',
    },
    {
      id: 'hub',
      name: 'project-management-robot',
      label: '爆米花机-对话型（对话枢纽 + 项目管理）',
      dir: 'ticket-pm/project-management-robot', // 项目根：push.js/package.json 所在（server/ 无 push 脚本，2026-09-16 运维台交互审计修复）
      repo: 'own',
      port: 3000,
      pm2Name: 'knowledge-tracker',
      nasDir: '/c/qianli/opt/knowledge-tracker/server',
      deploy: 'npm run push（根目录）',
      role: '所有对话/指令的唯一入口：@对话、基础指令、关键词监听与自动回答、抽奖（一个工作表=一个指令=一个奖池）、DDL 播报与逾期确认（含负责人群整合播报：逾期+临期跨群汇总 @章子赫，2026-09-22）、会议提醒、项目表；专项指令转发各服务。',
      listening: [
        '全部消息事件（gateway 转发）；群聊需 @机器人，私聊直接对话',
        'p2p：DDL 逾期确认回复（12 小时时效，超时次日播报重问）→ 值日分支（指令/图片，duty-bot 未接管时落回常规流；图片/文件双线：duty 照片凭证 + 发票采集观察转发 approval-bot，2026-09-25 v112 起）→ 基础指令（白名单）→ 对话',
        '群：@对话 → 值日群分支（看板仅 @ 触发、带不带 / 均可、@+纯图片静默、非管辖群值日指令回提示）→ 审批群分支 → 基础指令（静态表未命中接 抽奖动态指令，工作表名=指令名）→ 关键词自动回答（全群统一，未@也生效）；会议提醒对值日管辖群跳过（群级功能全关）',
        'GET /api/hub/policy（定制窗口：审批群/值日策略源/回答表范围/播报群全景只读）',
      ],
      commands: [
        '/help /lottery /<工作表名>（动态抽奖指令，一个工作表=一个指令=一个奖池，如 /抽奖） /status /test-ddl /keywords /autoreply /history（后五个为运维指令，不在群聊 /help 展示）',
        '/approval-* → approval-bot（:3002）',
        '/print-* → bambu（:3001）',
        '值日助手 / 我要请假 / 查询我的下一次值日 / 绑定 X / 打卡（主词，2026-09-13 起；是/口语变体兼容保留）/ 否 / 生成排班表 → duty-bot（:3006；带 / 前缀等效）',
      ],
      windows: [
        { m: 'GET', p: '/api/hub/policy', d: '定制项全景（审批群/值日策略源/回答表范围/播报群）' },
        { m: 'GET', p: '/api/hub/workload', d: '团队负载全景（工单+项目+被@三源评分聚合；运维台「团队负载」看板数据源；组别系数：宣运×0.5、重装/步兵/哨兵×1.2，每被@一次+0.01；ticket-bot/网关不可用各自降级标注）' },
        { m: 'GET', p: '/api/autoreplies/rules?table=group', d: '关键词回答表（未@群消息，可编辑）', kind: 'rules', table: 'group' },
        { m: 'GET', p: '/api/autoreplies/rules?table=mention', d: '@触发回答表（可编辑）', kind: 'rules', table: 'mention' },
        { m: 'POST', p: '/api/autoreplies/rules', d: '新增/更新关键词规则', kind: 'rule-edit' },
        { m: 'POST', p: '/api/autoreplies/rules/delete', d: '删除关键词规则', kind: 'rule-delete' },
        { m: 'POST', p: '/api/autoreplies/enabled', d: '启停回答表', kind: 'toggle' },
        { m: 'GET', p: '/api/lottery/rules', d: '抽奖配置（触发词/奖品/概率，可编辑）', kind: 'rules', table: 'lottery' },
        { m: 'POST', p: '/api/lottery/rules', d: '新增/更新奖池', kind: 'rule-edit' },
        { m: 'POST', p: '/api/lottery/rules/delete', d: '删除奖池', kind: 'rule-delete' },
        { m: 'POST', p: '/api/lottery/enabled', d: '启停抽奖', kind: 'toggle' },
        { m: 'GET', p: '/api/keywords/config', d: '关键词监听配置（千里论坛发言记录）' },
      ],
      permissions: [
        '审批群（APPROVAL_CHAT_ID）：整体切换为仅 /approval-*',
        '值日管辖群（duty-bot /api/duty/policy 下发，当前=快递申领群）：hub 基础指令关闭，看板「值日助手」仅 @ 或私聊触发；关键词回答全群统一（未@也生效，2026-09-13）',
        '私聊基础指令白名单 P2P_COMMAND_OPEN_IDS / P2P_COMMAND_CHAT_IDS（值日指令不限）',
        '抽奖：@机器人 发「/工作表名」即抽一次（抽奖配置表.xlsx 一个工作表=一个指令=一个奖池，复制表改名即新抽奖；值日管辖群可用；审批群不开放；私聊按指令白名单口径）；LOTTERY_CHAT_IDS 可收窄；动态进 /help',
      ],
      localRun: { script: 'server/src/index.js', cwd: '', env: {} },
      quickActions: [
        { id: 'install', label: 'npm install', cmd: 'npm install', cwd: '' },
        { id: 'test-duty', label: '值日分支 stub 测试', cmd: 'node scripts/stub-test-duty-branch.js', cwd: 'server' }, // 脚本在 server/scripts（依赖 server/src 相对路径）
        { id: 'test-ddl-leader', label: '负责人群整合播报 stub 测试', cmd: 'node scripts/stub-test-ddl-leader.js', cwd: 'server' },
      ],
      notes: 'v113 审批群裸词「接取」转发（2026-09-25）：交付卡领取回路，matchApprovalTake 放行（容忍尾部标点），转发载荷带 senderName/senderId 供 approval-bot 登记接取人；关键词自动回答表 .local.json 私有覆盖（真实回答不上传 git）；抽奖配置 .local.json 同口径守卫；2026-09-14 起 /help 不展示运维指令（/status /test-ddl /keywords /autoreply /history 仍可用）；DDL 播报事件写入动态广场（机器人项目看板）；2026-09-22 起每日 12:05 各群播报后负责人群补发「逾期+临期」整合卡（LEADER_WEBHOOK_URL/LEADER_CHAT_ID + 卡头 @章子赫，全空当日不发，webhook 只出布尔不出原文）；2026-09-25 v112 起 p2p 图片/文件 fire-and-forget 转发票采集（approval-bot /api/invoice/collect，X-API-Token，60s 超时，回执由 approval-bot 私聊发）',
    },
    {
      id: 'bambu',
      name: 'bambu-print-reservation',
      label: '打印预约（/print-*）',
      dir: 'bambu-print-reservation',
      repo: 'top',
      port: 3001,
      pm2Name: 'bambu-print-server',
      nasDir: '/c/qianli/opt/bambu-print-server',
      deploy: 'npm run push（纯 SFTP，无 git 步骤）',
      role: '打印预约域：/print-* 指令、预约审批、打印机控制；打印审批联动（审批事件）。',
      listening: ['不消费消息事件（hub 转发 /api/chat/command）', '审批事件（gateway 转发）', 'GET /api/print/policy（定制窗口：打印机/审批/分发参数全景只读）'],
      commands: ['/print-help /print-status /print-list /print-pending /print-ams /print-dispatch'],
      permissions: ['被动指令服务：仅接受 hub 转发'],
      localRun: { script: 'src/index.js', cwd: '', env: {} },
      quickActions: [
        { id: 'install', label: 'npm install', cmd: 'npm install', cwd: '' },
      ],
      windows: [
        { m: 'GET', p: '/api/print/policy', d: '打印机登记/审批通道/分发参数全景（只读）' },
      ],
      notes: 'push 无 git 步骤；版本锚点取顶层归档提交；v24 起分发引擎状态持久化（DISPATCH_STATE_FILE=/home/qianli/bambu-data/dispatch-state.json，重启不丢队列/打印中）；v25 起人工指定与自动匹配按打印机分发闸门互斥（分钟级 TOCTOU 关闭）；打印排队/开始/完成/失败事件写入动态广场（机器人项目看板）',
    },
    {
      id: 'approval',
      name: 'approval-bot',
      label: '财务审批（审批群 + 催办）',
      dir: 'approval-bot',
      repo: 'own',
      port: 3002,
      pm2Name: 'approval-bot',
      nasDir: '/c/qianli/opt/approval-bot',
      deploy: 'npm run push',
      role: '财务审批域：审批群 /approval-*、每周财务催办周报（催发票/报销单/转账）、每日待审批提醒、催发票私聊、发票采集与报销批次三件套。',
      listening: ['不消费消息事件（hub 转发 /api/chat/command）', 'p2p 回复轮询（催发票延期/无法提交识别 + 队员回票图片/PDF 采集）', 'GET /api/approval/policy（定制窗口：流程/审批人白名单/催办参数全景只读）', 'POST /api/ocr/transcribe（发票 OCR 转录）', 'POST /api/invoice/collect（hub 转发 p2p 交票采集）', 'POST /api/invoice/backfill（存量票回溯，管理端点）', '锁定批次→审批群交付卡（打印件/BOM/物料清单/投递底单 四附件+接取指引，人工触发即时发）', '审批群裸词「接取」（hub 转发带 senderName）→ 登记批次接取人'],
      commands: ['/approval-help /approval-list /approval-pending /approval-status /approval-urge /approval-batch', '接取 [批次号]（审批群回复领取交付包）'],
      windows: [
        { m: 'GET', p: '/api/approval/policy', d: '审批流程/审批人白名单/催办参数全景' },
        { m: 'GET', p: '/api/ocr/fields', d: '发票 OCR 字段提取规则全景（只读）' },
        { m: 'POST', p: '/api/ocr/fields', d: 'OCR 字段规则热改（action=set 整表替换/reset 恢复默认）' },
      ],
      permissions: ['仅服务审批群（BOT_CHAT_ID）', '定时任务：周报周一 18:00（含报销台账段）/ 每日待审批提醒 09:00 / 催发票私聊每日 10:30（宽限 14 天、每 2 天一催、上限 5 次、回复「延期 N 天/无法提交」或直接回票；均过静默闸门）', '发票 OCR（飞书官方接口，免费 20QPS）：需飞书后台开通 im:resource + optical_char_recognition + approval:approval:readonly + drive:drive'],
      localRun: { script: 'src/index.js', cwd: '', env: {} },
      quickActions: [
        { id: 'install', label: 'npm install', cmd: 'npm install', cwd: '' },
      ],
      notes: 'v49 交付包（2026-09-25，照财务《物料清单》模板+学校投递单实样）：lock 生成 物料清单（校格式，项目列=开票内容，缺失标黄）+投递底单（字段全预填含大写金额/转卡收款人，配置 BATCH_*/CQ_* 存 .env），摘要/笔序自动拼装落批次表；paid 回执附归档文件夹名建议；「接取」裸词领取登记接取人；提醒回落 open_id 已改通用变量名（REMINDER_FALLBACK_OPEN_ID_1/2）；v45 发票采集全链路：队员私聊/催办回票→三通道识别（PDF文本层/二维码/OCR）→采集台账（真源，审批base下「发票采集」「报销批次」两表）→/approval-batch 三件套（拟批/锁定回写报销单栏/打印PDF/BOM；v46 补 regen 附件自愈）；v46 全量复查批：/api/invoice/backfill 改 APPROVAL_CODE 驱动（.env 未配该键时端点按设计返 400 指引）、hub 转发超时对齐 60s、查重加锁；.ocr-fields.local.json 与 OCR_FIELDS_FILE 同 v44 口径',
    },
    {
      id: 'ticket',
      name: 'ticket-bot',
      label: '工单域（播报/接单/结单）',
      dir: 'ticket-pm/ticket-bot',
      repo: 'own',
      port: 3003,
      pm2Name: 'ticket-bot',
      nasDir: '/c/qianli/opt/ticket-bot',
      deploy: 'npm run push',
      role: '工单域：播报到组别群、@接单确认、搬运看板、结单提醒、未结单按负责人组别分桶 API；接单→审批任务自动通过。',
      listening: ['gateway 工单域例外直连：/ticket-* 指令、@机器人+「接单」', '审批事件（接单联动）', 'GET /api/tickets/policy（定制窗口：路由/审批节点/多人单窗口/组长全景只读）'],
      commands: ['接单/接单N（群内 @机器人）', '工单指令（/ticket-*）'],
      permissions: ['架构铁律唯一例外：允许消费工单域消息事件'],
      localRun: { script: 'src/index.js', cwd: '', env: {} },
      quickActions: [
        { id: 'install', label: 'npm install', cmd: 'npm install', cwd: '' },
      ],
      windows: [
        { m: 'GET', p: '/api/tickets/policy', d: '播报路由/审批节点/多人单窗口/组长映射/门禁全景（只读）' },
        { m: 'GET', p: '/api/tickets/workload-by-person', d: '未结单工单按人展开（open_id 粒度，负载视角不做路由过滤；hub /api/hub/workload 聚合数据源）' },
      ],
      notes: '多人接单批次已随 v61（f6f73e2）推送：出站 fetch 15s 超时、审批人解析失败不缓存自愈、接单队列复用全量记录、静默积压挪址 QUIET_BACKLOG_FILE；v64 起同群并发接单串行化（补充负责人合并写不再互相覆盖）；v65 起搬运人员口径=补充负责人全员（指定负责人公示即绑定入补充负责人，专项搬运废止；指定负责人本身不再直接入看板）；v66 起接单类消息按群实时队列门禁（无单群静默，不再回无待接单提示）；工单播报/接单/结单/审批自动通过事件写入动态广场（机器人项目看板）',
    },
    {
      id: 'duty',
      name: 'duty-bot',
      label: '值日提醒（排班/私信闭环）',
      dir: 'duty-bot',
      repo: 'own',
      port: 3006,
      pm2Name: 'duty-bot',
      nasDir: '/c/qianli/opt/duty-bot',
      deploy: 'npm run push',
      role: '值日域：排班生成与轮转/缺勤补偿、私信提醒与收口、照片凭证写表、值日助手（私信说明/群看板）、/api/duty/brief 数据接口、管辖策略下发（/api/duty/policy）、名册自动读通讯录。',
      listening: ['不消费消息事件（hub 转发 /api/chat/command）', 'GET /api/duty/policy → hub 消费（值日域管辖范畴/生效范畴单一事实来源）', 'GET /api/duty/roster、POST /api/duty/roster/refresh、GET|POST /api/duty/whitelist（名册/白名单定制窗口）'],
      commands: [
        '值日助手（p2p 用法 / group 看板带不带 / 均可，1h 限流）',
        '我要请假 → 确认请假（两步确认）/ 取消请假（请假当日空缺，2026-09-25 起） / 查询我的下一次值日 / 绑定 姓名 / 打卡 / 打卡了（完成打卡主词，2026-09-13 起）/ 否 / 生成排班表；「是」及口语变体（是的/好了/完成了/做完了/搞定 等）兼容保留，有当日询问会话时等同打卡',
        '生成排班表（名册 admin 专用）',
        '快递助手 / 快递（开 5 分钟登记窗口）/ 查询当前快递 / 已取n（多件必带编号）/ 全部已取——快递申领群 @ 或私聊（2026-09-17 快递助手，「快递」表）',
      ],
      windows: [
        { m: 'GET', p: '/api/duty/policy', d: '值日域管辖策略（可在线改写管辖群）' },
        { m: 'POST', p: '/api/duty/policy', d: '管辖范畴在线改写（groupChatIds）', kind: 'policy-edit' },
        { m: 'GET', p: '/api/duty/roster', d: '名册全景（通讯录同步，人数动态）' },
        { m: 'POST', p: '/api/duty/roster/refresh', d: '手动刷新通讯录名册', kind: 'action' },
        { m: 'GET', p: '/api/duty/whitelist', d: '白名单（值日排除名单，可增删）', kind: 'whitelist' },
        { m: 'POST', p: '/api/duty/whitelist', d: '白名单增删', kind: 'whitelist-edit' },
        { m: 'GET', p: '/api/duty/brief', d: '昨日/今日值日简报' },
      ],
      permissions: [
        '排班生成权限：名册 admin:true（或 DUTY_ADMIN_OPEN_IDS）',
        '定时任务：D-7 20:05 值日预告（2026-09-24）/ D-1 20:00 / 当日 12:00 值日看板播报（今日+昨日战报）/ 18:30 询问 / 23:00 收口前临门提醒（私信未完结者）/ 24:00 收口（写表不延迟；2026-09-17 起 22:00→24:00）/ 00:30 对账 / 每小时整点快递未取播报（EXPRESS_BROADCAST_SCHEDULE，无未取不发）（均过静默闸门）',
        '值日域管辖：DUTY_GROUP_CHAT_IDS 管辖群经 /api/duty/policy 下发，hub 群内闸门照此执行（含快递助手群内指令/取件词形/非@观察转发，2026-09-17）',
        '名册自动同步：启动/生成排班前/手动 refresh 读通讯录全员（open_id 直取），whitelist.json 为排除名单',
        '真实名册 config/members.json、whitelist.json 不进 git（push.js 显式 SFTP 上部署目标）',
        '排班参数：DUTY_WEEKLY_INSERTION_ALLOWANCE（v37 周插入容量，默认每周 2 条非请假位插入，超出顺延下周——防补偿安置把一周插成天天 4 人的「雪球」）',
      ],
      localRun: { script: 'src/index.js', cwd: '', env: {} },
      quickActions: [
        { id: 'install', label: 'npm install', cmd: 'npm install', cwd: '' },
        { id: 'test', label: '值日全量 stub 测试（7 套）', cmd: 'npm run test:schedule && npm run test:flow && npm run test:policy && npm run test:roster && npm run test:board && npm run test:express && npm run test:generate-place', cwd: '' },
        { id: 'table-check', label: '表格字段校验', cmd: 'npm run table:check', cwd: '' },
        { id: 'plaza-tables', label: '动态广场建表（幂等）', cmd: 'node scripts/create-plaza-tables.js', cwd: '' },
      ],
      notes: '表格已接线（机器人项目看板库·值日看板表，字段经 DUTY_FIELD_* 映射）；名册自动读通讯录（64 人全员入册，open_id 直取，whitelist.json 为排除名单——权威在部署目标侧，push 有备份+守卫，见顶层 AGENTS「运行时数据保护」）；值日完成/请假事件写入动态广场；接口 GET /api/duty/brief、GET /api/duty/policy、GET /api/duty/roster、GET|POST /api/duty/whitelist、POST /api/chat/command（转发载荷带 messageId，消息级幂等全路径生效；返回 {reply}）、/api/bot/test-*、POST /api/bot/rebalance（v37 排班重排：默认 dryRun 预览、confirm=true 执行，先自动全量备份到数据目录 backup/；X-API-Token）',
    },
    {
      id: 'wecom-attendance',
      name: 'wecom-attendance-bot',
      label: '考勤周报（企微数据→飞书播报）',
      dir: 'wecom-attendance-bot',
      repo: 'top',
      port: 3007,
      pm2Name: 'wecom-attendance',
      nasDir: '/c/qianli/opt/wecom-attendance-bot',
      deploy: 'npm run push（SFTP 直传，同 gateway 模式）',
      role: '企业微信考勤域：负责人群每周播报考勤打卡数据（周报卡 + CSV 明细），拉企微打卡 API 聚合，不碰考勤机硬件；播报主通道=飞书群机器人 webhook（v3），企微通道可选双发。',
      listening: [
        '不消费任何消息事件（飞书/企微都不收，纯定时任务）',
        '仅回环 127.0.0.1 监听，LAN 拓扑探测恒 ✗ 属正常（运维台拓扑图不列该端口）',
        '出站：企微 gettoken + checkin/getcheckindata（受自建应用可信 IP 限制）',
        '出站：企微群机器人 webhook/send + upload_media（key 即凭证，不走可信 IP）',
        '出站：飞书群自定义机器人 webhook 卡片（FEISHU_WEBHOOK_URL，签名可选；duty 看板卡同款链路）+ 可选经现有应用 im API 发 CSV 文件',
        '补发看门狗：每小时 5 分对表，漏播/失败自动补（周水位 lastSentWeekKey + 每通道投递水位，重试只补未送达通道；过静默闸门）',
      ],
      commands: ['HTTP API：GET /api/attendance/policy（全景只读） GET /api/attendance/preview?weekOffset=N（干跑预览） POST /api/attendance/members（名单增删，X-API-Token） POST /api/attendance/test-broadcast（真发/dryRun，X-API-Token） POST /api/attendance/import（打卡报表导入，X-API-Token；数据源=人肉周导，名单自动合并）'],
      permissions: ['定时播报：ATTENDANCE_BROADCAST_CRON（默认周一 09:30 上海时间，白天发送不落静默窗口）', '成员名单 config/members.json 不进 git（push 备份+守卫，权威在部署目标侧）'],
      windows: [
        { m: 'GET', p: '/api/attendance/policy', d: '播报参数/企微配置布尔/名单/水位全景（只读）' },
        { m: 'POST', p: '/api/attendance/members', d: '播报名单增删（add/remove）', kind: 'action',
          params: [
            { key: 'action', type: 'select', options: ['add', 'remove'], d: '动作' },
            { key: 'name', type: 'text', d: '姓名' },
            { key: 'userid', type: 'text', d: '企微 userid' },
          ] },
        { m: 'POST', p: '/api/attendance/test-broadcast', d: '手动播报（支持 dryRun 与周偏移）', kind: 'action',
          params: [
            { key: 'dryRun', type: 'checkbox', d: 'dryRun（只渲染不真发）' },
            { key: 'weekOffset', type: 'number', d: '周偏移(0=本周)' },
          ] },
        { m: 'GET', p: '/api/attendance/preview', d: '干跑预览（拉数渲染不发送，weekOffset 查询参数可选）' },
        { m: 'POST', p: '/api/attendance/import', d: '打卡报表导入（POST {dataBase64, filename?}，X-API-Token；kind 标注：运维台窗口不实现 base64 上传，走 SSH/curl）', kind: 'note' },
      ],
      localRun: { script: 'src/index.js', cwd: '', env: {} },
      quickActions: [
        { id: 'install', label: 'npm install', cmd: 'npm install', cwd: '' },
        { id: 'test', label: '全量 stub 测试', cmd: 'npm run test', cwd: '' },
      ],
      notes: 'v3 起（2026-09-15）播报并入现有飞书体系：主通道=飞书负责人群自定义机器人 webhook（连通性已真发验证），企微通道可选；CSV 飞书侧经现有应用 im API（FEISHU_CSV_CHAT_ID 未配则仅落盘）。v1 约束继续有效：企微打卡 API 约束=拉数跨度≤30天/userid 单批≤100（自动分批）/webhook 20条每分；拉数需自建应用+「打卡-可调用接口的应用」授权+可信 IP（家宽 IP 变动报 60020，告警卡会提示；webhook 播报不受可信 IP 限制）；周报用 markdown_v2（旧客户端表格退化纯文本，CSV 兜底）；「缺卡判定」需打卡规则接口对照班次，留 v2',
    },
    {
      id: 'dashboard',
      name: 'qianli-dashboard',
      label: '曼波大模型（本地运维台，仅本机）',
      dir: 'dashboard',
      repo: 'top',
      port: 3100,
      pm2Name: null,
      nasDir: null,
      deploy: '仅本机运行（node server.js），不部署',
      role: '全项目可视化运维：总览仪表台（服务状态矩阵/1h 时间线/24h 可用率/掉线事件、活跃看板=队员活跃+功能激活，队员活跃为正经使用口径：抽奖/关键词回答等娱乐功能不计入，2026-09-22；团队负载看板=工单+项目双源评分聚合，hub /api/hub/workload，2026-09-24）、网络拓扑看板（TCP 探测+LAN 设备发现+踢出/封禁，经小米路由器）、R14 看门狗（每小时 SSH 逐端口健康巡检，连 2 轮异常才告警）、端口职能/权限/指令清单、本地与主机(部署目标)服务状态、运行日志、更新状态；本地测试进程启停；npm push 等快捷指令。',
      listening: ['仅 127.0.0.1，无外部访问'],
      commands: ['HTTP API：/api/overview（含主机状态） /api/stats（总览仪表台：采样史/可用率/掉线事件） /api/activity（活跃看板：网关使用统计+各域 policy 激活聚合） /api/team-load（团队负载：hub 双源评分聚合，300s 缓存） /api/network 与 /api/network/lan（网络拓扑+LAN 设备发现） /api/network/lan/kick|ban|unban（设备踢出/封禁，经小米路由器） /api/router/status /api/egress-ip（出口 IP） /api/watchdog（R14 看门狗状态） /api/local/:id/start|stop|log /api/action/:id 与 /api/action/:id/log /api/nas/log/:name /api/nas/restart/:name /api/windows（定制窗口清单） /api/nas/api（SSH 代理直达部署目标本机接口）'],
      permissions: ['部署目标凭据直读 approval-bot/.env（不复制、不入库）'],
      localRun: null,
      quickActions: [],
      notes: '本文件 registry.js 是全项目权能清单的单一事实来源',
    },
  ],
};
